module example1;

/*
Generated by Entice Designer
Entice Designer written by Christopher E. Miller
www.dprogramming.com/entice.php
*/

import dfl.all;

import std.conv : to;


class Example1: dfl.form.Form
{
    // Do not modify or move this block of variables.
    //~Entice Designer variables begin here.
    dfl.label.Label label1;
    dfl.button.Button button1;
    dfl.button.CheckBox checkBox1;
    dfl.textbox.TextBox textBox1;
    dfl.button.RadioButton radioButton1;
    dfl.richtextbox.RichTextBox richTextBox1;
    dfl.groupbox.GroupBox groupBox1;
    dfl.listbox.ListBox listBox1;
    dfl.combobox.ComboBox comboBox1;
    dfl.progressbar.ProgressBar progressBar1;
    dfl.progressbar.ProgressBar progressBar2;
    dfl.picturebox.PictureBox pictureBox1;
    //~Entice Designer variables end here.


    this()
    {
        initializeExample1();

        //@  Other Example1 initialization code here.

    }


    private void initializeExample1()
    {
        // Do not manually modify this function.
        //~Entice Designer 0.8.5.02 code begins here.
        //~DFL Form
        text = "Example 1";
        clientSize = dfl.all.Size(408, 345);
        //~DFL dfl.label.Label=label1
        label1 = new dfl.label.Label();
        label1.name = "label1";
        label1.text = "Label with text";
        label1.textAlign = dfl.all.ContentAlignment.MIDDLE_CENTER;
        label1.bounds = dfl.all.Rect(8, 8, 92, 23);
        label1.parent = this;
        //~DFL dfl.button.Button=button1
        button1 = new dfl.button.Button();
        button1.name = "button1";
        button1.text = "Button";
        button1.bounds = dfl.all.Rect(112, 8, 91, 23);
        button1.parent = this;
        //~DFL dfl.button.CheckBox=checkBox1
        checkBox1 = new dfl.button.CheckBox();
        checkBox1.name = "checkBox1";
        checkBox1.text = "Check box";
        checkBox1.bounds = dfl.all.Rect(216, 8, 75, 23);
        checkBox1.parent = this;
        //~DFL dfl.textbox.TextBox=textBox1
        textBox1 = new dfl.textbox.TextBox();
        textBox1.name = "textBox1";
        textBox1.text = "Text box";
        textBox1.bounds = dfl.all.Rect(296, 8, 104, 23);
        textBox1.parent = this;
        //~DFL dfl.button.RadioButton=radioButton1
        radioButton1 = new dfl.button.RadioButton();
        radioButton1.name = "radioButton1";
        radioButton1.text = "Radio button";
        radioButton1.bounds = dfl.all.Rect(8, 40, 83, 23);
        radioButton1.parent = this;
        //~DFL dfl.richtextbox.RichTextBox=richTextBox1
        richTextBox1 = new dfl.richtextbox.RichTextBox();
        richTextBox1.name = "richTextBox1";
        richTextBox1.text = "Rich text box";
        richTextBox1.bounds = dfl.all.Rect(104, 40, 120, 120);
        richTextBox1.parent = this;
        //~DFL dfl.groupbox.GroupBox=groupBox1
        groupBox1 = new dfl.groupbox.GroupBox();
        groupBox1.name = "groupBox1";
        groupBox1.text = "Group box";
        groupBox1.bounds = dfl.all.Rect(232, 40, 168, 116);
        groupBox1.parent = this;
        //~DFL dfl.listbox.ListBox=listBox1
        listBox1 = new dfl.listbox.ListBox();
        listBox1.name = "listBox1";
        listBox1.bounds = dfl.all.Rect(8, 19, 144, 82);
        listBox1.parent = groupBox1;
        //~DFL dfl.combobox.ComboBox=comboBox1
        comboBox1 = new dfl.combobox.ComboBox();
        comboBox1.name = "comboBox1";
        comboBox1.text = "Combo box";
        comboBox1.bounds = dfl.all.Rect(8, 64, 88, 21);
        comboBox1.parent = this;
        //~DFL dfl.progressbar.ProgressBar=progressBar1
        progressBar1 = new dfl.progressbar.ProgressBar();
        progressBar1.name = "progressBar1";
        progressBar1.bounds = dfl.all.Rect(8, 96, 84, 23);
        progressBar1.parent = this;
        //~DFL dfl.progressbar.ProgressBar=progressBar2
        progressBar2 = new dfl.progressbar.ProgressBar();
        progressBar2.name = "progressBar2";
        progressBar2.bounds = dfl.all.Rect(8, 128, 84, 23);
        progressBar2.parent = this;
        //~DFL dfl.picturebox.PictureBox=pictureBox1
        pictureBox1 = new dfl.picturebox.PictureBox();
        pictureBox1.name = "pictureBox1";
        pictureBox1.bounds = dfl.all.Rect(288, 352, 32, 32);
        pictureBox1.parent = this;
        //~Entice Designer 0.8.5.02 code ends here.
    }
}


int main()
{
    int result = 0;

    try
    {
        // Application.enableVisualStyles();

        //@  Other application initialization code here.

        auto form = new Example1();
        form.progressBar2.value(100);

        Application.run();
    }
    catch(Exception o)
    {
        msgBox(to!wstring(o.toString()), "Fatal Error", MsgBoxButtons.OK, MsgBoxIcon.ERROR);

        result = 1;
    }

    return result;
}

