module mytab;

/*
Generated by Entice Designer
Entice Designer written by Christopher E. Miller
www.dprogramming.com/entice.php
*/

import dfl.all;


class MyTab: dfl.tabcontrol.TabPage
{
    // Do not modify or move this block of variables.
    //~Entice Designer variables begin here.
    dfl.label.Label label2;
    public dfl.button.Button button2;
    public dfl.textbox.TextBox textBox2;
    public dfl.button.Button button3;
    public dfl.button.Button button4;
    public dfl.button.Button button5;
    //~Entice Designer variables end here.


    this()
    {
        super("Custom tab");
        initializeMyTab();

        //@  Other MyTab initialization code here.

    }


    private void initializeMyTab()
    {
        // Do not manually modify this function.
        //~Entice Designer 0.8.5.02 code begins here.
        //~DFL TabPage
        //~DFL dfl.label.Label=label2
        label2 = new dfl.label.Label();
        label2.name = "label2";
        label2.text = "Label in tab control";
        label2.bounds = dfl.all.Rect(8, 8, 100, 23);
        label2.parent = this;
        //~DFL dfl.button.Button=button2
        button2 = new dfl.button.Button();
        button2.name = "button2";
        button2.text = "Button in tab control";
        button2.bounds = dfl.all.Rect(8, 40, 123, 23);
        button2.parent = this;
        //~DFL dfl.textbox.TextBox=textBox2
        textBox2 = new dfl.textbox.TextBox();
        textBox2.name = "textBox2";
        textBox2.text = "Text box in tab control";
        textBox2.bounds = dfl.all.Rect(8, 80, 120, 23);
        textBox2.parent = this;
        //~DFL dfl.button.Button=button3
        button3 = new dfl.button.Button();
        button3.name = "button3";
        button3.text = "Open file";
        button3.bounds = dfl.all.Rect(8, 110, 80, 23);
        button3.parent = this;
        //~DFL dfl.button.Button=button4
        button4 = new dfl.button.Button();
        button4.name = "button4";
        button4.text = "Open folder";
        button4.bounds = dfl.all.Rect(96, 110, 80, 23);
        button4.parent = this;
        //~DFL dfl.button.Button=button5
        button5 = new dfl.button.Button();
        button5.name = "button5";
        button5.text = "Save file";
        button5.bounds = dfl.all.Rect(8, 140, 80, 23);
        button5.parent = this;
        //~Entice Designer 0.8.5.02 code ends here.
        

        void button3_clicked(Object sender, EventArgs ea)
        {
            auto ofd = new OpenFileDialog();
            ofd.title("OpenFileDialog example");
            ofd.filter("Arbitrary extension files (*.extension)|*.extension|All files (*.*)|*.*");
            auto res = ofd.showDialog(null);
            if (res == DialogResult.OK) {
                textBox2.text(ofd.fileName);
            }
        }

        void button4_clicked(Object sender, EventArgs ea)
        {
            auto fbd = new FolderBrowserDialog();
            fbd.description("FolderBrowserDialog example\nThis description is multi-line!");
            auto res = fbd.showDialog(null);
            if (res == DialogResult.OK) {
                textBox2.text(fbd.selectedPath);
            }
        }

        void button5_clicked(Object sender, EventArgs ea)
        {
            auto sfd = new SaveFileDialog();
            sfd.title("SaveFileDialog example");
            auto res = sfd.showDialog(null);
            if (res == DialogResult.OK) {
                textBox2.text(sfd.fileName);
            }
    
        }

        button3.click.addHandler(&button3_clicked);
        button4.click.addHandler(&button4_clicked);
        button5.click.addHandler(&button5_clicked);
    }
}

